version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=kong-service_db_1
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=SuperSecret!23
      - DATABASE_PORT=5432
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecret!23
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080